name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.1.java11'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          # To use Clojure CLI 1.10.1.561 based on tools.deps
          cli: '1.10.1.469'

      - name: Build jar
        run: clojure -A:pack:build-lib

      - name: Publish package
        run:  clojure ./src/kepler16/deploy.clj | sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
